### ISSUE TITLE
darwin breakage on gio-windowing

### ISSUE THREAD

**Issue by gedw99** [rajveermalviya/go-webgpu#132]
I noticed you merged the darwin branch into main branch.

On latest main branch , darwin is broken.

Can you help advise what might be the problem ?

``` 

apple@x-MacBook-Pro-2 gio-windowing % go build .
apple@x-MacBook-Pro-2 gio-windowing % ls
gio-windowing		main.go			shader.wgsl		surface_android.go	surface_darwin.go	surface_linux.go	surface_windows.go
apple@x-MacBook-Pro-2 gio-windowing % ./gio-windowing 
panic: TODO

goroutine 19 [running]:
main.getSurfaceDescriptor(...)
	/Users/apple/workspace/go/src/github.com/rajveermalviya/go-webgpu/examples/gio-windowing/surface_darwin.go:11
main.loop.func1()
	/Users/apple/workspace/go/src/github.com/rajveermalviya/go-webgpu/examples/gio-windowing/main.go:70 +0x27
sync.(*Once).doSlow(0x0?, 0xc000038480?)
	/usr/local/opt/go/libexec/src/sync/once.go:68 +0xc2
sync.(*Once).Do(...)
	/usr/local/opt/go/libexec/src/sync/once.go:59
main.loop(0xc000070000)
	/Users/apple/workspace/go/src/github.com/rajveermalviya/go-webgpu/examples/gio-windowing/main.go:69 +0x6d2
main.main.func1()
	/Users/apple/workspace/go/src/github.com/rajveermalviya/go-webgpu/examples/gio-windowing/main.go:44 +0x77
created by main.main
	/Users/apple/workspace/go/src/github.com/rajveermalviya/go-webgpu/examples/gio-windowing/main.go:42 +0x25
apple@x-MacBook-Pro-2 gio-windowing % 


```

**Comment by gedw99** [comment]
sorry i just noticed  that darwin is not implemented yet: https://github.com/rajveermalviya/go-webgpu/blob/main/examples/gio-windowing/surface_darwin.go#L11

**Comment by gedw99** [comment]
i just pulled latest.

Now for gio-windowing example i get:
./main.go:70:34: undefined: getSurfaceDescriptor

Much less errors.

**Comment by gedw99** [comment]
i reopened it. Hope you do not mind..

**Comment by rajveermalviya** [comment]
yep, it's because gio-windowing example currently lacks support for darwin. I mainly have it in just to showcase android support.
you should instead be able to run glfw-based examples (triangle, cube, boids) on darwin.

would really appreciate if someone with a mac is willing to shoot a PR.
I haven't looked into how gio exposes Cocoa handles, doubt it would be much different than how glfw does it.

https://github.com/rajveermalviya/go-webgpu/blob/507e0ba4017222a6fd9200cb7c62bd78970f98d0/examples/triangle/surface_darwin.go

**Comment by gedw99** [comment]
I dont know how to do the Cocoa handles. am mostly pure golang developer
I know that in the GIOUI code base they recently had work done for Platform Views, which is slightly related.
https://todo.sr.ht/~eliasnaur/gio/428

wish i could be more help.

**Comment by rajveermalviya** [comment]
while implementing it (see #199) it seems this is not possible with Gio's current api.

Gio's current api prevents using it as a standalone windowing library (atleast for macos & i assume ios too),
because the metal layer provided by [ViewEvent](https://pkg.go.dev/gioui.org/app?GOOS=darwin#ViewEvent) cannot be resized
from a separate goroutine (non main thread).

we can merge #199 as is, but that would not be good idea as resizing the window will fail.

**Comment by gedw99** [comment]
the latest GIO should help and you can also use it as standalone.

https://github.com/gioui/gio-example/blob/main/glfw is a simple example doing it which might help ?
